baseURL = "http://localhost:1313/"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Example - CV"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#4088d1"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
